/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root"
import { Route as LoginRouteImport } from "./routes/login"
import { Route as IndexRouteImport } from "./routes/index"
import { Route as SourcesIndexRouteImport } from "./routes/sources.index"
import { Route as SettingsIndexRouteImport } from "./routes/settings.index"
import { Route as FocusesIndexRouteImport } from "./routes/focuses.index"
import { Route as FeedIndexRouteImport } from "./routes/feed.index"
import { Route as EditionsIndexRouteImport } from "./routes/editions.index"
import { Route as BookmarksIndexRouteImport } from "./routes/bookmarks.index"
import { Route as SourcesNewRouteImport } from "./routes/sources.new"
import { Route as SourcesSourceIdRouteImport } from "./routes/sources.$sourceId"
import { Route as FocusesNewRouteImport } from "./routes/focuses.new"
import { Route as FocusesFocusIdRouteImport } from "./routes/focuses.$focusId"
import { Route as EditionsNewRouteImport } from "./routes/editions.new"
import { Route as EditionsConfigIdRouteImport } from "./routes/editions.$configId"
import { Route as SourcesSourceIdIndexRouteImport } from "./routes/sources.$sourceId.index"
import { Route as FocusesFocusIdIndexRouteImport } from "./routes/focuses.$focusId.index"
import { Route as SourcesSourceIdEditRouteImport } from "./routes/sources.$sourceId.edit"
import { Route as FocusesFocusIdEditRouteImport } from "./routes/focuses.$focusId.edit"
import { Route as EditionsConfigIdEditRouteImport } from "./routes/editions.$configId.edit"
import { Route as SourcesSourceIdArticlesArticleIdRouteImport } from "./routes/sources.$sourceId.articles.$articleId"
import { Route as EditionsConfigIdIssuesEditionIdRouteImport } from "./routes/editions.$configId.issues.$editionId"
import { Route as EditionsConfigIdIssuesEditionIdIndexRouteImport } from "./routes/editions.$configId.issues.$editionId.index"
import { Route as EditionsConfigIdIssuesEditionIdMagazineRouteImport } from "./routes/editions.$configId.issues.$editionId.magazine"

const LoginRoute = LoginRouteImport.update({
  id: "/login",
  path: "/login",
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any)
const SourcesIndexRoute = SourcesIndexRouteImport.update({
  id: "/sources/",
  path: "/sources/",
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: "/settings/",
  path: "/settings/",
  getParentRoute: () => rootRouteImport,
} as any)
const FocusesIndexRoute = FocusesIndexRouteImport.update({
  id: "/focuses/",
  path: "/focuses/",
  getParentRoute: () => rootRouteImport,
} as any)
const FeedIndexRoute = FeedIndexRouteImport.update({
  id: "/feed/",
  path: "/feed/",
  getParentRoute: () => rootRouteImport,
} as any)
const EditionsIndexRoute = EditionsIndexRouteImport.update({
  id: "/editions/",
  path: "/editions/",
  getParentRoute: () => rootRouteImport,
} as any)
const BookmarksIndexRoute = BookmarksIndexRouteImport.update({
  id: "/bookmarks/",
  path: "/bookmarks/",
  getParentRoute: () => rootRouteImport,
} as any)
const SourcesNewRoute = SourcesNewRouteImport.update({
  id: "/sources/new",
  path: "/sources/new",
  getParentRoute: () => rootRouteImport,
} as any)
const SourcesSourceIdRoute = SourcesSourceIdRouteImport.update({
  id: "/sources/$sourceId",
  path: "/sources/$sourceId",
  getParentRoute: () => rootRouteImport,
} as any)
const FocusesNewRoute = FocusesNewRouteImport.update({
  id: "/focuses/new",
  path: "/focuses/new",
  getParentRoute: () => rootRouteImport,
} as any)
const FocusesFocusIdRoute = FocusesFocusIdRouteImport.update({
  id: "/focuses/$focusId",
  path: "/focuses/$focusId",
  getParentRoute: () => rootRouteImport,
} as any)
const EditionsNewRoute = EditionsNewRouteImport.update({
  id: "/editions/new",
  path: "/editions/new",
  getParentRoute: () => rootRouteImport,
} as any)
const EditionsConfigIdRoute = EditionsConfigIdRouteImport.update({
  id: "/editions/$configId",
  path: "/editions/$configId",
  getParentRoute: () => rootRouteImport,
} as any)
const SourcesSourceIdIndexRoute = SourcesSourceIdIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => SourcesSourceIdRoute,
} as any)
const FocusesFocusIdIndexRoute = FocusesFocusIdIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => FocusesFocusIdRoute,
} as any)
const SourcesSourceIdEditRoute = SourcesSourceIdEditRouteImport.update({
  id: "/edit",
  path: "/edit",
  getParentRoute: () => SourcesSourceIdRoute,
} as any)
const FocusesFocusIdEditRoute = FocusesFocusIdEditRouteImport.update({
  id: "/edit",
  path: "/edit",
  getParentRoute: () => FocusesFocusIdRoute,
} as any)
const EditionsConfigIdEditRoute = EditionsConfigIdEditRouteImport.update({
  id: "/edit",
  path: "/edit",
  getParentRoute: () => EditionsConfigIdRoute,
} as any)
const SourcesSourceIdArticlesArticleIdRoute =
  SourcesSourceIdArticlesArticleIdRouteImport.update({
    id: "/articles/$articleId",
    path: "/articles/$articleId",
    getParentRoute: () => SourcesSourceIdRoute,
  } as any)
const EditionsConfigIdIssuesEditionIdRoute =
  EditionsConfigIdIssuesEditionIdRouteImport.update({
    id: "/issues/$editionId",
    path: "/issues/$editionId",
    getParentRoute: () => EditionsConfigIdRoute,
  } as any)
const EditionsConfigIdIssuesEditionIdIndexRoute =
  EditionsConfigIdIssuesEditionIdIndexRouteImport.update({
    id: "/",
    path: "/",
    getParentRoute: () => EditionsConfigIdIssuesEditionIdRoute,
  } as any)
const EditionsConfigIdIssuesEditionIdMagazineRoute =
  EditionsConfigIdIssuesEditionIdMagazineRouteImport.update({
    id: "/magazine",
    path: "/magazine",
    getParentRoute: () => EditionsConfigIdIssuesEditionIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute
  "/login": typeof LoginRoute
  "/editions/$configId": typeof EditionsConfigIdRouteWithChildren
  "/editions/new": typeof EditionsNewRoute
  "/focuses/$focusId": typeof FocusesFocusIdRouteWithChildren
  "/focuses/new": typeof FocusesNewRoute
  "/sources/$sourceId": typeof SourcesSourceIdRouteWithChildren
  "/sources/new": typeof SourcesNewRoute
  "/bookmarks/": typeof BookmarksIndexRoute
  "/editions/": typeof EditionsIndexRoute
  "/feed/": typeof FeedIndexRoute
  "/focuses/": typeof FocusesIndexRoute
  "/settings/": typeof SettingsIndexRoute
  "/sources/": typeof SourcesIndexRoute
  "/editions/$configId/edit": typeof EditionsConfigIdEditRoute
  "/focuses/$focusId/edit": typeof FocusesFocusIdEditRoute
  "/sources/$sourceId/edit": typeof SourcesSourceIdEditRoute
  "/focuses/$focusId/": typeof FocusesFocusIdIndexRoute
  "/sources/$sourceId/": typeof SourcesSourceIdIndexRoute
  "/editions/$configId/issues/$editionId": typeof EditionsConfigIdIssuesEditionIdRouteWithChildren
  "/sources/$sourceId/articles/$articleId": typeof SourcesSourceIdArticlesArticleIdRoute
  "/editions/$configId/issues/$editionId/magazine": typeof EditionsConfigIdIssuesEditionIdMagazineRoute
  "/editions/$configId/issues/$editionId/": typeof EditionsConfigIdIssuesEditionIdIndexRoute
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute
  "/login": typeof LoginRoute
  "/editions/$configId": typeof EditionsConfigIdRouteWithChildren
  "/editions/new": typeof EditionsNewRoute
  "/focuses/new": typeof FocusesNewRoute
  "/sources/new": typeof SourcesNewRoute
  "/bookmarks": typeof BookmarksIndexRoute
  "/editions": typeof EditionsIndexRoute
  "/feed": typeof FeedIndexRoute
  "/focuses": typeof FocusesIndexRoute
  "/settings": typeof SettingsIndexRoute
  "/sources": typeof SourcesIndexRoute
  "/editions/$configId/edit": typeof EditionsConfigIdEditRoute
  "/focuses/$focusId/edit": typeof FocusesFocusIdEditRoute
  "/sources/$sourceId/edit": typeof SourcesSourceIdEditRoute
  "/focuses/$focusId": typeof FocusesFocusIdIndexRoute
  "/sources/$sourceId": typeof SourcesSourceIdIndexRoute
  "/sources/$sourceId/articles/$articleId": typeof SourcesSourceIdArticlesArticleIdRoute
  "/editions/$configId/issues/$editionId/magazine": typeof EditionsConfigIdIssuesEditionIdMagazineRoute
  "/editions/$configId/issues/$editionId": typeof EditionsConfigIdIssuesEditionIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  "/": typeof IndexRoute
  "/login": typeof LoginRoute
  "/editions/$configId": typeof EditionsConfigIdRouteWithChildren
  "/editions/new": typeof EditionsNewRoute
  "/focuses/$focusId": typeof FocusesFocusIdRouteWithChildren
  "/focuses/new": typeof FocusesNewRoute
  "/sources/$sourceId": typeof SourcesSourceIdRouteWithChildren
  "/sources/new": typeof SourcesNewRoute
  "/bookmarks/": typeof BookmarksIndexRoute
  "/editions/": typeof EditionsIndexRoute
  "/feed/": typeof FeedIndexRoute
  "/focuses/": typeof FocusesIndexRoute
  "/settings/": typeof SettingsIndexRoute
  "/sources/": typeof SourcesIndexRoute
  "/editions/$configId/edit": typeof EditionsConfigIdEditRoute
  "/focuses/$focusId/edit": typeof FocusesFocusIdEditRoute
  "/sources/$sourceId/edit": typeof SourcesSourceIdEditRoute
  "/focuses/$focusId/": typeof FocusesFocusIdIndexRoute
  "/sources/$sourceId/": typeof SourcesSourceIdIndexRoute
  "/editions/$configId/issues/$editionId": typeof EditionsConfigIdIssuesEditionIdRouteWithChildren
  "/sources/$sourceId/articles/$articleId": typeof SourcesSourceIdArticlesArticleIdRoute
  "/editions/$configId/issues/$editionId/magazine": typeof EditionsConfigIdIssuesEditionIdMagazineRoute
  "/editions/$configId/issues/$editionId/": typeof EditionsConfigIdIssuesEditionIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | "/"
    | "/login"
    | "/editions/$configId"
    | "/editions/new"
    | "/focuses/$focusId"
    | "/focuses/new"
    | "/sources/$sourceId"
    | "/sources/new"
    | "/bookmarks/"
    | "/editions/"
    | "/feed/"
    | "/focuses/"
    | "/settings/"
    | "/sources/"
    | "/editions/$configId/edit"
    | "/focuses/$focusId/edit"
    | "/sources/$sourceId/edit"
    | "/focuses/$focusId/"
    | "/sources/$sourceId/"
    | "/editions/$configId/issues/$editionId"
    | "/sources/$sourceId/articles/$articleId"
    | "/editions/$configId/issues/$editionId/magazine"
    | "/editions/$configId/issues/$editionId/"
  fileRoutesByTo: FileRoutesByTo
  to:
    | "/"
    | "/login"
    | "/editions/$configId"
    | "/editions/new"
    | "/focuses/new"
    | "/sources/new"
    | "/bookmarks"
    | "/editions"
    | "/feed"
    | "/focuses"
    | "/settings"
    | "/sources"
    | "/editions/$configId/edit"
    | "/focuses/$focusId/edit"
    | "/sources/$sourceId/edit"
    | "/focuses/$focusId"
    | "/sources/$sourceId"
    | "/sources/$sourceId/articles/$articleId"
    | "/editions/$configId/issues/$editionId/magazine"
    | "/editions/$configId/issues/$editionId"
  id:
    | "__root__"
    | "/"
    | "/login"
    | "/editions/$configId"
    | "/editions/new"
    | "/focuses/$focusId"
    | "/focuses/new"
    | "/sources/$sourceId"
    | "/sources/new"
    | "/bookmarks/"
    | "/editions/"
    | "/feed/"
    | "/focuses/"
    | "/settings/"
    | "/sources/"
    | "/editions/$configId/edit"
    | "/focuses/$focusId/edit"
    | "/sources/$sourceId/edit"
    | "/focuses/$focusId/"
    | "/sources/$sourceId/"
    | "/editions/$configId/issues/$editionId"
    | "/sources/$sourceId/articles/$articleId"
    | "/editions/$configId/issues/$editionId/magazine"
    | "/editions/$configId/issues/$editionId/"
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  EditionsConfigIdRoute: typeof EditionsConfigIdRouteWithChildren
  EditionsNewRoute: typeof EditionsNewRoute
  FocusesFocusIdRoute: typeof FocusesFocusIdRouteWithChildren
  FocusesNewRoute: typeof FocusesNewRoute
  SourcesSourceIdRoute: typeof SourcesSourceIdRouteWithChildren
  SourcesNewRoute: typeof SourcesNewRoute
  BookmarksIndexRoute: typeof BookmarksIndexRoute
  EditionsIndexRoute: typeof EditionsIndexRoute
  FeedIndexRoute: typeof FeedIndexRoute
  FocusesIndexRoute: typeof FocusesIndexRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
  SourcesIndexRoute: typeof SourcesIndexRoute
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/login": {
      id: "/login"
      path: "/login"
      fullPath: "/login"
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/": {
      id: "/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/sources/": {
      id: "/sources/"
      path: "/sources"
      fullPath: "/sources/"
      preLoaderRoute: typeof SourcesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/settings/": {
      id: "/settings/"
      path: "/settings"
      fullPath: "/settings/"
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/focuses/": {
      id: "/focuses/"
      path: "/focuses"
      fullPath: "/focuses/"
      preLoaderRoute: typeof FocusesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/feed/": {
      id: "/feed/"
      path: "/feed"
      fullPath: "/feed/"
      preLoaderRoute: typeof FeedIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/editions/": {
      id: "/editions/"
      path: "/editions"
      fullPath: "/editions/"
      preLoaderRoute: typeof EditionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/bookmarks/": {
      id: "/bookmarks/"
      path: "/bookmarks"
      fullPath: "/bookmarks/"
      preLoaderRoute: typeof BookmarksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/sources/new": {
      id: "/sources/new"
      path: "/sources/new"
      fullPath: "/sources/new"
      preLoaderRoute: typeof SourcesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/sources/$sourceId": {
      id: "/sources/$sourceId"
      path: "/sources/$sourceId"
      fullPath: "/sources/$sourceId"
      preLoaderRoute: typeof SourcesSourceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/focuses/new": {
      id: "/focuses/new"
      path: "/focuses/new"
      fullPath: "/focuses/new"
      preLoaderRoute: typeof FocusesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/focuses/$focusId": {
      id: "/focuses/$focusId"
      path: "/focuses/$focusId"
      fullPath: "/focuses/$focusId"
      preLoaderRoute: typeof FocusesFocusIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/editions/new": {
      id: "/editions/new"
      path: "/editions/new"
      fullPath: "/editions/new"
      preLoaderRoute: typeof EditionsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/editions/$configId": {
      id: "/editions/$configId"
      path: "/editions/$configId"
      fullPath: "/editions/$configId"
      preLoaderRoute: typeof EditionsConfigIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/sources/$sourceId/": {
      id: "/sources/$sourceId/"
      path: "/"
      fullPath: "/sources/$sourceId/"
      preLoaderRoute: typeof SourcesSourceIdIndexRouteImport
      parentRoute: typeof SourcesSourceIdRoute
    }
    "/focuses/$focusId/": {
      id: "/focuses/$focusId/"
      path: "/"
      fullPath: "/focuses/$focusId/"
      preLoaderRoute: typeof FocusesFocusIdIndexRouteImport
      parentRoute: typeof FocusesFocusIdRoute
    }
    "/sources/$sourceId/edit": {
      id: "/sources/$sourceId/edit"
      path: "/edit"
      fullPath: "/sources/$sourceId/edit"
      preLoaderRoute: typeof SourcesSourceIdEditRouteImport
      parentRoute: typeof SourcesSourceIdRoute
    }
    "/focuses/$focusId/edit": {
      id: "/focuses/$focusId/edit"
      path: "/edit"
      fullPath: "/focuses/$focusId/edit"
      preLoaderRoute: typeof FocusesFocusIdEditRouteImport
      parentRoute: typeof FocusesFocusIdRoute
    }
    "/editions/$configId/edit": {
      id: "/editions/$configId/edit"
      path: "/edit"
      fullPath: "/editions/$configId/edit"
      preLoaderRoute: typeof EditionsConfigIdEditRouteImport
      parentRoute: typeof EditionsConfigIdRoute
    }
    "/sources/$sourceId/articles/$articleId": {
      id: "/sources/$sourceId/articles/$articleId"
      path: "/articles/$articleId"
      fullPath: "/sources/$sourceId/articles/$articleId"
      preLoaderRoute: typeof SourcesSourceIdArticlesArticleIdRouteImport
      parentRoute: typeof SourcesSourceIdRoute
    }
    "/editions/$configId/issues/$editionId": {
      id: "/editions/$configId/issues/$editionId"
      path: "/issues/$editionId"
      fullPath: "/editions/$configId/issues/$editionId"
      preLoaderRoute: typeof EditionsConfigIdIssuesEditionIdRouteImport
      parentRoute: typeof EditionsConfigIdRoute
    }
    "/editions/$configId/issues/$editionId/": {
      id: "/editions/$configId/issues/$editionId/"
      path: "/"
      fullPath: "/editions/$configId/issues/$editionId/"
      preLoaderRoute: typeof EditionsConfigIdIssuesEditionIdIndexRouteImport
      parentRoute: typeof EditionsConfigIdIssuesEditionIdRoute
    }
    "/editions/$configId/issues/$editionId/magazine": {
      id: "/editions/$configId/issues/$editionId/magazine"
      path: "/magazine"
      fullPath: "/editions/$configId/issues/$editionId/magazine"
      preLoaderRoute: typeof EditionsConfigIdIssuesEditionIdMagazineRouteImport
      parentRoute: typeof EditionsConfigIdIssuesEditionIdRoute
    }
  }
}

interface EditionsConfigIdIssuesEditionIdRouteChildren {
  EditionsConfigIdIssuesEditionIdMagazineRoute: typeof EditionsConfigIdIssuesEditionIdMagazineRoute
  EditionsConfigIdIssuesEditionIdIndexRoute: typeof EditionsConfigIdIssuesEditionIdIndexRoute
}

const EditionsConfigIdIssuesEditionIdRouteChildren: EditionsConfigIdIssuesEditionIdRouteChildren =
  {
    EditionsConfigIdIssuesEditionIdMagazineRoute:
      EditionsConfigIdIssuesEditionIdMagazineRoute,
    EditionsConfigIdIssuesEditionIdIndexRoute:
      EditionsConfigIdIssuesEditionIdIndexRoute,
  }

const EditionsConfigIdIssuesEditionIdRouteWithChildren =
  EditionsConfigIdIssuesEditionIdRoute._addFileChildren(
    EditionsConfigIdIssuesEditionIdRouteChildren,
  )

interface EditionsConfigIdRouteChildren {
  EditionsConfigIdEditRoute: typeof EditionsConfigIdEditRoute
  EditionsConfigIdIssuesEditionIdRoute: typeof EditionsConfigIdIssuesEditionIdRouteWithChildren
}

const EditionsConfigIdRouteChildren: EditionsConfigIdRouteChildren = {
  EditionsConfigIdEditRoute: EditionsConfigIdEditRoute,
  EditionsConfigIdIssuesEditionIdRoute:
    EditionsConfigIdIssuesEditionIdRouteWithChildren,
}

const EditionsConfigIdRouteWithChildren =
  EditionsConfigIdRoute._addFileChildren(EditionsConfigIdRouteChildren)

interface FocusesFocusIdRouteChildren {
  FocusesFocusIdEditRoute: typeof FocusesFocusIdEditRoute
  FocusesFocusIdIndexRoute: typeof FocusesFocusIdIndexRoute
}

const FocusesFocusIdRouteChildren: FocusesFocusIdRouteChildren = {
  FocusesFocusIdEditRoute: FocusesFocusIdEditRoute,
  FocusesFocusIdIndexRoute: FocusesFocusIdIndexRoute,
}

const FocusesFocusIdRouteWithChildren = FocusesFocusIdRoute._addFileChildren(
  FocusesFocusIdRouteChildren,
)

interface SourcesSourceIdRouteChildren {
  SourcesSourceIdEditRoute: typeof SourcesSourceIdEditRoute
  SourcesSourceIdIndexRoute: typeof SourcesSourceIdIndexRoute
  SourcesSourceIdArticlesArticleIdRoute: typeof SourcesSourceIdArticlesArticleIdRoute
}

const SourcesSourceIdRouteChildren: SourcesSourceIdRouteChildren = {
  SourcesSourceIdEditRoute: SourcesSourceIdEditRoute,
  SourcesSourceIdIndexRoute: SourcesSourceIdIndexRoute,
  SourcesSourceIdArticlesArticleIdRoute: SourcesSourceIdArticlesArticleIdRoute,
}

const SourcesSourceIdRouteWithChildren = SourcesSourceIdRoute._addFileChildren(
  SourcesSourceIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  EditionsConfigIdRoute: EditionsConfigIdRouteWithChildren,
  EditionsNewRoute: EditionsNewRoute,
  FocusesFocusIdRoute: FocusesFocusIdRouteWithChildren,
  FocusesNewRoute: FocusesNewRoute,
  SourcesSourceIdRoute: SourcesSourceIdRouteWithChildren,
  SourcesNewRoute: SourcesNewRoute,
  BookmarksIndexRoute: BookmarksIndexRoute,
  EditionsIndexRoute: EditionsIndexRoute,
  FeedIndexRoute: FeedIndexRoute,
  FocusesIndexRoute: FocusesIndexRoute,
  SettingsIndexRoute: SettingsIndexRoute,
  SourcesIndexRoute: SourcesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
